# The URL of your website.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "/"

# Title of your site
title = "Rahjaytee"
logo = "favicon.ico"

# Your copyright notice - appears in site footer.
# To display a copyright symbol, type `&copy;`.
copyright = "&copy; Ren Jie Tan 2018"

theme = "minimal-academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
#preserveTaxonomyNames = true
paginate = 10

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Get last modified date for content from Git?
enableGitInfo = false

[outputs]
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/readfiles/bfconfig/
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab.
  fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
  smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).

[params]
  # Your details.
  name = "Ren Jie"
  bio = "Don't Forget to Have Fun"

  avatar = "portrait.jpg"  # Specify an avatar image (in `static/img/` folder) or delete value to disable avatar.

  location = "Singapore"


  # Discussion link (e.g. link to a forum, mailing list, or chat).
  #   Uncomment line below to use.
  #   discussion = { name = "Discuss", url = "https://discourse.gohugo.io" }

  # Date and time format (refer to Go's date format: http://fuckinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Jan 2, 2006"
  #   Examples: "3:04 pm" or "15:04"
  time_format = "3:04 PM"

  # Display comment count? Requires commenting to be enabled.
  comment_count = true

  # Enable native social sharing buttons?
  sharing = true

  # Privacy pack
  #   Show a cookie consent message to visitors
  #   Anonymize IP in Google Analytics (if enabled)
  privacy_pack = true

  [[params.social]]
    icon = "instagram"
    icon_pack = "fa"
    link = "//instagram.com/rahjaytee"
    text = "Instagram"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//linkedin.com/in/renjietan"
    text = "LinkedIn"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/rahjaytee"
    text = "Twitter"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/notha99y"
    text = "Github"

# Taxonomies.
# [taxonomies]
#   tag = "tags"
#   category = "categories"
#   publication_type = "publication_types"
